### ISSUE TITLE
Error when  trying to run nastran.exe

### ISSUE THREAD

**Issue by zinfridd** [Foadsf/NASTRAN-95#5]
i am getting this error, when trying to run nastran.exe:

./nastran.exe -v
At line 34 of file /home/B14-DEMO4/NASTRAN-95/bin/nastrn.f
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x3ff0157aa in ???
#1  0x3fefa3cb4 in ???
#2  0x3feed149b in ???
#3  0x3fefa50cc in ???
#4  0x3ff0336da in ???
#5  0x3fefa863f in ???
#6  0x3fef926eb in ???
#7  0x1004017af in ???
#8  0x1009c90d3 in ???
#9  0x7ff8e24a8092 in ???
#10  0x7ff8e24a5e07 in ???
#11  0x7ff8e24a5e85 in ???
#12  0xffffffffffffffff in ???

Can you help me with this?

**Comment by fisichel3** [comment]
Hi Zinfridd,
There is no nastran.exe file, but there is a nastrn.exe. You don't want to run this directly. Instead, run the script file nastran. Here are some answers to expected problems. 1. Even after you set the execute bits, the script returns "./nastran: Command not found." 
What I had to do is open the script in an text editor. I used emacs. I copied the entirety of the script and pasted into an emacs buffer. I then deleted the nastran file with "rm nastran". In emacs, I created a new file nastran and pasted the contents of the script. The script ran fine. Finally, I moved the new file to nastran with "mv nastran2 nastran" 
You will need to edit the nastran script. At the very top, there are three paths that have "bob" in them. replace those paths to the ones that are specific to your machine. Once you do that, the script will output something like this:
                             NASTRAN
 
  (i)  Input file       ===> d01000a.inp
  (o)  Output file      ===> d01000a.out
  (l)  Logfile          ===> d01000a.log
  (s)  Script file      ===> d01000a.cmd
  (pu) Punch file       ===> none
  (pl) Plot file        ===> none
  (c)  Checkpoint NPTP  ===> d01000a.nptp
  (d)  Checkpoint dict. ===> d01000a.dic
  (r)  Restart OPTP     ===> none
  (ou) FTN11 file       ===> none
  (in) FTN12 file       ===> none
  (s1) SOF1 file        ===> none
  (s2) SOF2 file        ===> none
  (i1) FTN15 file       ===> none
  (i2) FTN16 file       ===> none
 
  (oc) Memory for Open Core    ===> 2000000
  (im) In-Memory DB Allocation ===> 12000000
  (w)  Work Directory ===> /home/fisichel/Documents/nascalcs/NASTRAN-95/bin/temp21436
  (g)  To create shell script and execute NASTRAN
  (a)  Abort without building shell script
 Specify Option ===> 
enter g
he shell script d01000a.cmd was successfully created
Do you want to execute this problem now? (y or n) ===> 
enter y
Do you want to run in foreground or background? (f or b) ===> 
enter f
==== NASTRAN is beginning execution of d01000a ====
/home/fisichel/Documents/nascalcs/NASTRAN-95/bin/nastrn.exe: 1: Syntax error: "(" unexpected
===== NASTRAN has completed problem d01000a =====
Best Regards,
Chris

**Comment by fisichel3** [comment]
One more thought. You might need to install csh on your machine. On Debian, that is sudo apt-get install csh.
